package com.coffeemaster.app.services.export

import com.coffeemaster.app.models.Report
import org.apache.poi.xwpf.usermodel.ParagraphAlignment
import org.apache.poi.xwpf.usermodel.XWPFDocument
import java.io.ByteArrayOutputStream

object DocxGenerator {
    fun generateReportDocx(report: Report): ByteArray {
        val doc = XWPFDocument()
        val p = doc.createParagraph()
        p.alignment = ParagraphAlignment.CENTER
        val run = p.createRun()
        run.isBold = true
        run.setFontSize(16)
        run.setText("Coffee Master Report")

        val meta = doc.createParagraph()
        val r2 = meta.createRun()
        r2.setText("Report ID: ${report.id}")
        r2.addBreak()
        r2.setText("Generated by: ${report.generatedBy}")
        r2.addBreak()
        r2.setText("Generated at: ${report.generatedAt}")

        try {
            val summary = report.data.summary
            val s = doc.createParagraph().createRun()
            s.setText("Total Revenue: ${summary.totalRevenue}")
            s.addBreak()
            s.setText("Total Expenses: ${summary.totalExpenses}")
            s.addBreak()
            s.setText("Net Profit: ${summary.netProfit}")
        } catch (e: Exception) {
            // ignore
        }

        val out = ByteArrayOutputStream()
        doc.write(out)
        doc.close()
        return out.toByteArray()
    }
}
